# Generated by Django 2.2.3 on 2019-12-30 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название по-русски')),
                ('title_en', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Название по-английски')),
                ('title_jp', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Название по-японски')),
                ('img_url', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('next_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pokemon_entities.Pokemon', verbose_name='В кого эволюционирует')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon_entities.Pokemon', verbose_name='Из кого эволюционировал')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Координата широты')),
                ('lon', models.FloatField(verbose_name='Координата долготы')),
                ('appeared_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата появления')),
                ('disappeared_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата исчезновения')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='Уровень')),
                ('health', models.IntegerField(blank=True, null=True, verbose_name='Здоровье')),
                ('strength', models.IntegerField(blank=True, null=True, verbose_name='Атака')),
                ('defence', models.IntegerField(blank=True, null=True, verbose_name='Защита')),
                ('stamina', models.IntegerField(blank=True, null=True, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.Pokemon', verbose_name='Покемон')),
            ],
        ),
    ]
